package com.kurzdigital.vds.vds

enum class VdsType {
    VISA,
    EMERGENCY_TRAVEL,
    EMERGENCY_TRAVEL_SINGLE_JOURNEY,
    EMERGENCY_TRAVEL_WITH_BIO,
    SUPERVISED_ANTIGEN_TEST,
    VACCINATION_CERTIFICATE,
    TAX_STAMP,
    PHARMAPACK,
    GENERAL_PURPOSE,
    VEHICLE_VIGNETTE,
    ADDRESS_STICKER_GERMAN_PASSPORT,
    ADDRESS_STICKER_GERMAN_ID_CARD,
    SUPPLEMENT_SHEET,
    RESIDENCE_PERMIT,
    SOCIAL_INSURANCE_CARD,
    ARRIVAL_ATTESTATION,
    DEMECAN_PATIENT_ID,
    MALI_WSL,
    HEALTH_INSURANCE_CARD,
    TICKET_DEMONSTRATOR,
}
