package com.kurzdigital.vds.vds

enum class VdsType {
    VISA,
    EMERGENCY_TRAVEL,
    SUPERVISED_ANTIGEN_TEST,
    VACCINATION_CERTIFICATE,
    TAX_STAMP,
    PHARMAPACK,
    GENERAL_PURPOSE,
    VEHICLE_VIGNETTE,
    ADDRESS_STICKER_GERMAN_PASSPORT,
    ADDRESS_STICKER_GERMAN_ID_CARD,
    SUPPLEMENT_SHEET,
    RESIDENCE_PERMIT,
    SOCIAL_INSURANCE_CARD,
    ARRIVAL_ATTESTATION
}
